url: https://y7kim.github.io
baseurl: 

# Site settings
title: Avast Cyklo Šauer MTB team
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people-fathers:
- name: Tomáš Šauer
  pic: sauer_tomas
  position: Zakladatel a majitel Cyklo Šauer, táta Olivky
  social:
    - title: globe
      url: http://www.cyklosauer.cz

- name: Michal Trs
  pic: trs_michal
  position: Poháněč v Avast Software, táta Matěje a Kubíka
  social:
    - title: twitter
      url: https://twitter.com/misak19
    - title: google-plus
      url: https://plus.google.com/+MichalTrs/posts
    - title: linkedin
      url: https://cz.linkedin.com/in/michaltrs

- name: Dan Sedláček
  pic: sedlacek_dan
  position: Hlavní poháněč týmu, táta Mikiho

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty